spring:
  application:
    name: brian
  profiles:
    active: dev

mybatis-plus:
  global-config:
    banner: false

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus,env,beans
      base-path: /metrics
  server:
    port: 9080